# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: cimg/node:16.20.2

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout
      - run: |
          if [ "${CIRCLE_BRANCH}" == "acceptance" ]; then
            touch ~/repo/.env
            echo "NODE_ENV=staging" >> ~/repo/.env
            echo "REACT_APP_BASE_URL=https://company-info-bright-c6c99ec34e11.herokuapp.com/" >> ~/repo/.env
          fi

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: sudo apt update
      - run: sudo apt install rsync
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - deploy:
          command: |
            if [ "${CIRCLE_BRANCH}" == "acceptance" ]; then
              rsync -avz -e "ssh -o 'StrictHostKeyChecking no'" ~/repo/* webdev@87.233.181.243:/data/www/companyinfo.brightdigital.dev/public_html/ --delete
            fi
